import type { ComponentType } from "react";
import {
  BarChart3,
  Clock,
  Cpu,
  Database,
  FileText,
  GitBranch,
  Grid3X3,
  Layers,
  Search,
  Server,
  Star,
} from "lucide-react";
import {
  CassandraIcon,
  ClickHouseIcon,
  CouchbaseIcon,
  CsvIcon,
  DuckDbIcon,
  ElasticsearchIcon,
  FirebaseIcon,
  HiveIcon,
  InfluxDbIcon,
  MariaDbIcon,
  MongoDbIcon,
  MysqlIcon,
  Neo4jIcon,
  OracleIcon,
  ParquetIcon,
  PostgresIcon,
  RedisIcon,
  S3Icon,
  SqliteIcon,
  SqlServerIcon,
} from "@/components/connections/DriverIcons";

export interface DriverOption {
  id: string;
  backendDriver: "postgres" | "mysql" | "sqlite";
  name: string;
  Icon: ComponentType<{ className?: string }>;
  categories: string[];
  enabled: boolean;
  description: string;
}

export const CATEGORIES = [
  { id: "all", label: "All", Icon: Grid3X3 },
  { id: "popular", label: "Popular", Icon: Star },
  { id: "sql", label: "SQL", Icon: Database },
  { id: "nosql", label: "NoSQL", Icon: Layers },
  { id: "analytical", label: "Analytical", Icon: BarChart3 },
  { id: "files", label: "Files", Icon: FileText },
  { id: "embedded", label: "Embedded", Icon: Cpu },
  { id: "timeseries", label: "Timeseries", Icon: Clock },
  { id: "hadoop", label: "Hadoop / BigData", Icon: Server },
  { id: "search", label: "Full-text Search", Icon: Search },
  { id: "graph", label: "Graph Databases", Icon: GitBranch },
] as const;

export type CategoryId = (typeof CATEGORIES)[number]["id"];

export const DRIVERS: DriverOption[] = [
  {
    id: "postgresql",
    backendDriver: "postgres",
    name: "PostgreSQL",
    Icon: PostgresIcon,
    categories: ["all", "popular", "sql"],
    enabled: true,
    description: "Advanced open-source relational database",
  },
  {
    id: "mysql",
    backendDriver: "mysql",
    name: "MySQL",
    Icon: MysqlIcon,
    categories: ["all", "popular", "sql"],
    enabled: true,
    description: "Most popular open-source database",
  },
  {
    id: "sqlite",
    backendDriver: "sqlite",
    name: "SQLite",
    Icon: SqliteIcon,
    categories: ["all", "popular", "sql", "embedded", "files"],
    enabled: true,
    description: "Lightweight embedded database",
  },
  {
    id: "mariadb",
    backendDriver: "mysql",
    name: "MariaDB",
    Icon: MariaDbIcon,
    categories: ["all", "sql"],
    enabled: false,
    description: "MySQL fork with extra features",
  },
  {
    id: "sqlserver",
    backendDriver: "postgres",
    name: "SQL Server",
    Icon: SqlServerIcon,
    categories: ["all", "popular", "sql"],
    enabled: false,
    description: "Microsoft relational database",
  },
  {
    id: "oracle",
    backendDriver: "postgres",
    name: "Oracle",
    Icon: OracleIcon,
    categories: ["all", "sql"],
    enabled: false,
    description: "Enterprise relational database",
  },
  {
    id: "mongodb",
    backendDriver: "postgres",
    name: "MongoDB",
    Icon: MongoDbIcon,
    categories: ["all", "popular", "nosql"],
    enabled: false,
    description: "Document-oriented NoSQL database",
  },
  {
    id: "redis",
    backendDriver: "postgres",
    name: "Redis",
    Icon: RedisIcon,
    categories: ["all", "popular", "nosql", "timeseries"],
    enabled: false,
    description: "In-memory key-value store",
  },
  {
    id: "cassandra",
    backendDriver: "postgres",
    name: "Cassandra",
    Icon: CassandraIcon,
    categories: ["all", "nosql"],
    enabled: false,
    description: "Distributed wide-column store",
  },
  {
    id: "couchbase",
    backendDriver: "postgres",
    name: "Couchbase",
    Icon: CouchbaseIcon,
    categories: ["all", "nosql"],
    enabled: false,
    description: "Distributed document database",
  },
  {
    id: "clickhouse",
    backendDriver: "postgres",
    name: "ClickHouse",
    Icon: ClickHouseIcon,
    categories: ["all", "analytical", "sql"],
    enabled: false,
    description: "Column-oriented analytical database",
  },
  {
    id: "duckdb",
    backendDriver: "sqlite",
    name: "DuckDB",
    Icon: DuckDbIcon,
    categories: ["all", "analytical", "sql", "embedded"],
    enabled: false,
    description: "Analytical embedded database",
  },
  {
    id: "neo4j",
    backendDriver: "postgres",
    name: "Neo4j",
    Icon: Neo4jIcon,
    categories: ["all", "graph"],
    enabled: false,
    description: "Native graph database",
  },
  {
    id: "influxdb",
    backendDriver: "postgres",
    name: "InfluxDB",
    Icon: InfluxDbIcon,
    categories: ["all", "timeseries"],
    enabled: false,
    description: "Time-series database",
  },
  {
    id: "csv",
    backendDriver: "sqlite",
    name: "CSV",
    Icon: CsvIcon,
    categories: ["all", "files"],
    enabled: false,
    description: "Comma-separated values files",
  },
  {
    id: "parquet",
    backendDriver: "sqlite",
    name: "Parquet",
    Icon: ParquetIcon,
    categories: ["all", "files"],
    enabled: false,
    description: "Apache Parquet columnar format",
  },
  {
    id: "hive",
    backendDriver: "postgres",
    name: "Apache Hive",
    Icon: HiveIcon,
    categories: ["all", "hadoop"],
    enabled: false,
    description: "Data warehouse on Hadoop",
  },
  {
    id: "elasticsearch",
    backendDriver: "postgres",
    name: "Elasticsearch",
    Icon: ElasticsearchIcon,
    categories: ["all", "search", "nosql"],
    enabled: false,
    description: "Search and analytics engine",
  },
  {
    id: "firebase",
    backendDriver: "postgres",
    name: "Firebase",
    Icon: FirebaseIcon,
    categories: ["all", "nosql", "popular"],
    enabled: false,
    description: "Google realtime cloud database",
  },
  {
    id: "s3",
    backendDriver: "sqlite",
    name: "Amazon S3",
    Icon: S3Icon,
    categories: ["all", "files", "popular"],
    enabled: false,
    description: "Cloud object storage",
  },
];

export function getDriverById(id: string): DriverOption | undefined {
  return DRIVERS.find((driver) => driver.id === id);
}
